
modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/vectorwing/FarmersDelight/issues"
license = "MIT License"

[[mods]]
modId="moresigns"
version = "1.20.1-1.2.4"
displayName="More Signs"
displayURL="https://github.com/duperez/moreSigns"
logoFile="logo.png"
logoBlur=false
authors="duperez, LoosaZ"
description="Custom build of moreSigns made for TortuguitaSMP"
itemIcon="moresigns:black_canvas_sign"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.moresigns]]
    modId="forge"
    mandatory=true
    versionRange = "[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moresigns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,]"
    ordering="NONE"
    side="BOTH"
