package duperez.moresigns.common.registry;

import duperez.moresigns.common.block.entity.CanvasSignBlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import duperez.moresigns.MoreSigns;

public class ModBlockEntityTypes
{
	public static final DeferredRegister<BlockEntityType<?>> TILES = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, MoreSigns.MODID);

	public static final RegistryObject<BlockEntityType<CanvasSignBlockEntity>> CANVAS_SIGN = TILES.register("canvas_sign",
			() -> BlockEntityType.Builder.of(CanvasSignBlockEntity::new,
							ModBlocks.CANVAS_SIGN.get(),
							ModBlocks.WHITE_CANVAS_SIGN.get(),
							ModBlocks.ORANGE_CANVAS_SIGN.get(),
							ModBlocks.MAGENTA_CANVAS_SIGN.get(),
							ModBlocks.LIGHT_BLUE_CANVAS_SIGN.get(),
							ModBlocks.YELLOW_CANVAS_SIGN.get(),
							ModBlocks.LIME_CANVAS_SIGN.get(),
							ModBlocks.PINK_CANVAS_SIGN.get(),
							ModBlocks.GRAY_CANVAS_SIGN.get(),
							ModBlocks.LIGHT_GRAY_CANVAS_SIGN.get(),
							ModBlocks.CYAN_CANVAS_SIGN.get(),
							ModBlocks.PURPLE_CANVAS_SIGN.get(),
							ModBlocks.BLUE_CANVAS_SIGN.get(),
							ModBlocks.BROWN_CANVAS_SIGN.get(),
							ModBlocks.GREEN_CANVAS_SIGN.get(),
							ModBlocks.RED_CANVAS_SIGN.get(),
							ModBlocks.BLACK_CANVAS_SIGN.get(),
							ModBlocks.CANVAS_WALL_SIGN.get(),
							ModBlocks.ORANGE_PURPLE_SIGN.get(),
							ModBlocks.GREEN_GRADIENT_SIGN.get(),
							ModBlocks.ANTHONY_SIGN.get(),
							ModBlocks.HOTPINK_SIGN.get(),
							ModBlocks.INDIGO_SIGN.get(),
							ModBlocks.LIGHT_PINK_SIGN.get(),
							ModBlocks.LOOSAZ_SIGN.get(),
							ModBlocks.SPADES_SIGN.get(),
							ModBlocks.JINX_SIGN.get(),
							ModBlocks.ANHANGA_SIGN.get(),
							ModBlocks.MABHETIEL_SIGN.get(),
							ModBlocks.GOLD_SIGN.get(),
							ModBlocks.POMPOM_SIGN.get(),
							ModBlocks.RABBIT_SIGN.get(),
							ModBlocks.SODA_SIGN.get(),
							ModBlocks.CYBER_SIGN.get(),
							ModBlocks.AUTISM_SIGN.get(),
							ModBlocks.MARY_SIGN.get(),
							ModBlocks.MEG_SIGN.get(),
							ModBlocks.DELTA_SIGN.get(),
							ModBlocks.JACK_SIGN.get(),
							ModBlocks.KALYPSO_SIGN.get(),
							ModBlocks.M1_SIGN.get(),
							ModBlocks.MONA_SIGN.get(),
							ModBlocks.MOON_SIGN.get(),
							ModBlocks.MICHAEL_SIGN.get(),
							ModBlocks.UKO_SIGN.get(),
							ModBlocks.JAY_SIGN.get(),
							ModBlocks.CELYNE_SIGN.get(),
							ModBlocks.PEPPER_SIGN.get(),
							ModBlocks.EPSILON_SIGN.get(),
							ModBlocks.HAVARTI_SIGN.get(),
							ModBlocks.MINERVA_SIGN.get(),
							ModBlocks.RUNE_SIGN.get(),
							ModBlocks.LAMBDA_SIGN.get(),
							ModBlocks.OMICRON_SIGN.get(),
							ModBlocks.PSI_SIGN.get(),
							ModBlocks.TAU_SIGN.get(),
							ModBlocks.WHITE_CANVAS_WALL_SIGN.get(),
							ModBlocks.ORANGE_CANVAS_WALL_SIGN.get(),
							ModBlocks.MAGENTA_CANVAS_WALL_SIGN.get(),
							ModBlocks.LIGHT_BLUE_CANVAS_WALL_SIGN.get(),
							ModBlocks.YELLOW_CANVAS_WALL_SIGN.get(),
							ModBlocks.LIME_CANVAS_WALL_SIGN.get(),
							ModBlocks.PINK_CANVAS_WALL_SIGN.get(),
							ModBlocks.GRAY_CANVAS_WALL_SIGN.get(),
							ModBlocks.LIGHT_GRAY_CANVAS_WALL_SIGN.get(),
							ModBlocks.CYAN_CANVAS_WALL_SIGN.get(),
							ModBlocks.PURPLE_CANVAS_WALL_SIGN.get(),
							ModBlocks.BLUE_CANVAS_WALL_SIGN.get(),
							ModBlocks.BROWN_CANVAS_WALL_SIGN.get(),
							ModBlocks.GREEN_CANVAS_WALL_SIGN.get(),
							ModBlocks.RED_CANVAS_WALL_SIGN.get(),
							ModBlocks.GREEN_GRADIENT_WALL_SIGN.get(),
							ModBlocks.ORANGE_PURPLE_CANVAS_WALL_SIGN.get(),
							ModBlocks.ANTHONY_WALL_SIGN.get(),
							ModBlocks.HOTPINK_WALL_SIGN.get(),
							ModBlocks.INDIGO_WALL_SIGN.get(),
							ModBlocks.LIGHT_PINK_WALL_SIGN.get(),
							ModBlocks.LOOSAZ_WALL_SIGN.get(),
							ModBlocks.SPADES_WALL_SIGN.get(),
							ModBlocks.ANHANGA_WALL_SIGN.get(),
							ModBlocks.MABHETIEL_WALL_SIGN.get(),
							ModBlocks.GOLD_WALL_SIGN.get(),
							ModBlocks.POMPOM_WALL_SIGN.get(),
							ModBlocks.RABBIT_WALL_SIGN.get(),
							ModBlocks.SODA_WALL_SIGN.get(),
							ModBlocks.CYBER_WALL_SIGN.get(),
							ModBlocks.JINX_WALL_SIGN.get(),
							ModBlocks.AUTISM_WALL_SIGN.get(),
							ModBlocks.MARY_WALL_SIGN.get(),
							ModBlocks.MEG_WALL_SIGN.get(),
							ModBlocks.DELTA_WALL_SIGN.get(),
							ModBlocks.JACK_WALL_SIGN.get(),
							ModBlocks.KALYPSO_WALL_SIGN.get(),
							ModBlocks.M1_WALL_SIGN.get(),
							ModBlocks.MICHAEL_WALL_SIGN.get(),
							ModBlocks.MONA_WALL_SIGN.get(),
							ModBlocks.MOON_WALL_SIGN.get(),
							ModBlocks.UKO_WALL_SIGN.get(),
							ModBlocks.JAY_WALL_SIGN.get(),
							ModBlocks.CELYNE_WALL_SIGN.get(),
							ModBlocks.PEPPER_WALL_SIGN.get(),
							ModBlocks.EPSILON_WALL_SIGN.get(),
							ModBlocks.HAVARTI_WALL_SIGN.get(),
							ModBlocks.MINERVA_WALL_SIGN.get(),
							ModBlocks.RUNE_WALL_SIGN.get(),
							ModBlocks.LAMBDA_WALL_SIGN.get(),
							ModBlocks.OMICRON_WALL_SIGN.get(),
							ModBlocks.PSI_WALL_SIGN.get(),
							ModBlocks.TAU_WALL_SIGN.get(),
							ModBlocks.BLACK_CANVAS_WALL_SIGN.get())
					.build(null));
}
